TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += dbExample1.db
DB += dbExample2.db
#DB += eyesVersion.db
#file "db/dbExample1.db" {
#file db/dbExample2.db {
#DB += user.substitutions

DB += greateyes.db

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

